apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/nginx/access.log
        Tag           nginx.access
        DB            /var/log/flb_nginx.db
        Refresh_Interval 5
        Read_from_Head  true

    [OUTPUT]
        Name          stdout
        Match         *
  parsers.conf: |
    [PARSER]
        Name         nginx_parser
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On

